Fixed rubocop and foodcritic and added necessary files
osuosl-cookbooks/osl-varnish pull request #4
Opened 2017-01-05 19:55 UTC by cthalmann

Chefspec tests need to be added to osl-varnish. In order to pass rake, this cookbook has to pass rubocop and foodcritic before even getting to chefspec. This PR fixes rubocop and foodcritic errors. I also used chef generate in order to add necessary files, such as .kitchen.yml and the Rakefile.

2017-01-05 21:27 UTC, fahlmant submitted a review, later dismissed

2017-01-05 21:27 UTC, fahlmant commented on .rubocop.yml
> +Metrics/BlockLength:
Not needed now

2017-01-05 21:27 UTC, fahlmant commented on spec/default_spec.rb
> +      end
Since it's a small, one recipe cookbook, adding all the tests here may be a good idea. Thoughts @ramereth ?

2017-01-05 21:32 UTC, ramereth commented on spec/default_spec.rb
> +      end
Let's keep that in a different PR for now.

2017-01-05 21:34 UTC, ramereth commented on .rubocop.yml
> +Metrics/BlockLength:
Let's go ahead and keep it. We'll need it when we upgrade chefdk soon.

2017-01-05 21:35 UTC, ramereth requested changes

2017-01-05 21:35 UTC, ramereth commented on spec/spec_helper.rb
> +}.freeze
Please remove Debian 8.

2017-01-05 21:36 UTC, fahlmant approved these changes
Once Ramereth's comments are resolved

2017-01-05 23:50 UTC, ramereth approved these changes

2017-01-06 00:19 UTC, cthalmann commented
!bump patch ~

2017-01-06 00:19 UTC, merged

2017-01-06 00:20 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.0.1.  Have a nice day!